### ISSUE TITLE
Bibliography items require volume and journal

### ISSUE THREAD

**Issue by txsmith** [mjwsteenbergen/markender#84]
Some citations don't have a journal or volume associated. Markender seems to be unable to render references like this:
![image](https://user-images.githubusercontent.com/5946422/46669900-022e6b00-cbd1-11e8-8315-57cad2e70d50.png)

While in LaTeX it gets listed as:
![image](https://user-images.githubusercontent.com/5946422/46669928-18d4c200-cbd1-11e8-9fdd-bc3336a8cda1.png)

**Comment by mjwsteenbergen** [comment]
This is resolved with version [1.2.0](https://github.com/mjwsteenbergen/markender/commit/ad575de4de8787355448d41106b2ed9592c7dda8). Not only will it show the key in bibliography, you can also set your own by setting the id:

```
    <md-bib-doi id=your-citation-key>10.1109/5.771073</md-bib-doi>
```

**Comment by mjwsteenbergen** [comment]
Following [this](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Standard_templates) it is required to have a journal for an article, but not to have a volume. Will update this

**Comment by txsmith** [comment]
Do you support `@misc` in that case?

**Comment by mjwsteenbergen** [comment]
Yes, all of the [following](https://github.com/mjwsteenbergen/markender/blob/master/src/components/md-bib-item/md-bib-item.ts#L35) are allowed.
