### ISSUE TITLE
How do I cite a reference from doi?

### ISSUE THREAD

**Issue by txsmith** [mjwsteenbergen/markender#85]
If I try to cite a reference provided via the `md-bib-doi` element, it produces a "Missing Link":
![image](https://user-images.githubusercontent.com/5946422/46670097-884ab180-cbd1-11e8-88ee-bd6c56b7d5f5.png)

With the following code:

```
Test [1]

<md-bib>
  <md-bib-doi>10.1007/s002360050095</md-bib-doi>
</md-bib>
```

How can I refer to these DOIs?

**Comment by mjwsteenbergen** [comment]
This is resolved with version [1.2.0](https://github.com/mjwsteenbergen/markender/commit/ad575de4de8787355448d41106b2ed9592c7dda8). Not only will it show the key in bibliography, you can also set your own by setting the id:

```
    <md-bib-doi id=your-citation-key>10.1109/5.771073</md-bib-doi>
```
