### ISSUE TITLE
Sequence of multiple citations.

### ISSUE THREAD

**Issue by txsmith** [mjwsteenbergen/markender#86]
In LaTeX it is possible to produce multiple citations in one block like:
`\cite{paper1, work2}`
which produces:
`blablabla [1,2]`

Would this be possible to do in markender? 
Moreover, the following will render the citations literally as typed instead of links:
`blablabla [paper1] [paper2] `

**Comment by mjwsteenbergen** [comment]
Closed by 45b11f65f82d61d8173d6eaf49733e1409b63e37
